services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: usuario
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - ./DB:/var/lib/mysql
      - ./config:/docker-entrypoint-initdb.d
    networks:
      - backend

networks:
  backend:
